//-----------------------------------------------
//
//	This file is part of the Siv3D Engine.
//
//	Licensed under the MIT License.
//
//-----------------------------------------------

# include "Siv3DTest.hpp"
# include <type_traits>
# include <utility>
# include <Siv3D/Geometry2D/Overlaps.hpp>

namespace
{
	template <class A, class B, class = void>
	struct HasGeometry2DOverlaps : std::false_type {};

	template <class A, class B>
	struct HasGeometry2DOverlaps<A, B, std::void_t<decltype(
		Geometry2D::Overlaps(std::declval<const A&>(), std::declval<const B&>()))>>
		: std::is_same<decltype(Geometry2D::Overlaps(
			std::declval<const A&>(), std::declval<const B&>())), bool> {};
}

TEST_CASE("Geometry2D.Overlaps.FreeFunctionAvailability")
{
	static_assert(HasGeometry2DOverlaps<Point, Point>::value == false);
	static_assert(HasGeometry2DOverlaps<Point, Vec2>::value == false);
	static_assert(HasGeometry2DOverlaps<Point, Line>::value == false);
	static_assert(HasGeometry2DOverlaps<Point, LineString>::value == false);
	static_assert(HasGeometry2DOverlaps<Point, Bezier2>::value == false);
	static_assert(HasGeometry2DOverlaps<Point, Bezier3>::value == false);
	static_assert(HasGeometry2DOverlaps<Point, Rect>::value == false);
	static_assert(HasGeometry2DOverlaps<Point, RectF>::value == false);
	static_assert(HasGeometry2DOverlaps<Point, Circle>::value == false);
	static_assert(HasGeometry2DOverlaps<Point, Ellipse>::value == false);
	static_assert(HasGeometry2DOverlaps<Point, SuperEllipse>::value == false);
	static_assert(HasGeometry2DOverlaps<Point, Triangle>::value == false);
	static_assert(HasGeometry2DOverlaps<Point, Quad>::value == false);
	static_assert(HasGeometry2DOverlaps<Point, RoundRect>::value == false);
	static_assert(HasGeometry2DOverlaps<Point, Polygon>::value == false);
	static_assert(HasGeometry2DOverlaps<Point, MultiPolygon>::value == false);
	static_assert(HasGeometry2DOverlaps<Vec2, Point>::value == false);
	static_assert(HasGeometry2DOverlaps<Vec2, Vec2>::value == false);
	static_assert(HasGeometry2DOverlaps<Vec2, Line>::value == false);
	static_assert(HasGeometry2DOverlaps<Vec2, LineString>::value == false);
	static_assert(HasGeometry2DOverlaps<Vec2, Bezier2>::value == false);
	static_assert(HasGeometry2DOverlaps<Vec2, Bezier3>::value == false);
	static_assert(HasGeometry2DOverlaps<Vec2, Rect>::value == false);
	static_assert(HasGeometry2DOverlaps<Vec2, RectF>::value == false);
	static_assert(HasGeometry2DOverlaps<Vec2, Circle>::value == false);
	static_assert(HasGeometry2DOverlaps<Vec2, Ellipse>::value == false);
	static_assert(HasGeometry2DOverlaps<Vec2, SuperEllipse>::value == false);
	static_assert(HasGeometry2DOverlaps<Vec2, Triangle>::value == false);
	static_assert(HasGeometry2DOverlaps<Vec2, Quad>::value == false);
	static_assert(HasGeometry2DOverlaps<Vec2, RoundRect>::value == false);
	static_assert(HasGeometry2DOverlaps<Vec2, Polygon>::value == false);
	static_assert(HasGeometry2DOverlaps<Vec2, MultiPolygon>::value == false);
	static_assert(HasGeometry2DOverlaps<Line, Point>::value == false);
	static_assert(HasGeometry2DOverlaps<Line, Vec2>::value == false);
	static_assert(HasGeometry2DOverlaps<Line, Line>::value == false);
	static_assert(HasGeometry2DOverlaps<Line, LineString>::value == false);
	static_assert(HasGeometry2DOverlaps<Line, Bezier2>::value == false);
	static_assert(HasGeometry2DOverlaps<Line, Bezier3>::value == false);
	static_assert(HasGeometry2DOverlaps<Line, Rect>::value == false);
	static_assert(HasGeometry2DOverlaps<Line, RectF>::value == false);
	static_assert(HasGeometry2DOverlaps<Line, Circle>::value == false);
	static_assert(HasGeometry2DOverlaps<Line, Ellipse>::value == false);
	static_assert(HasGeometry2DOverlaps<Line, SuperEllipse>::value == false);
	static_assert(HasGeometry2DOverlaps<Line, Triangle>::value == false);
	static_assert(HasGeometry2DOverlaps<Line, Quad>::value == false);
	static_assert(HasGeometry2DOverlaps<Line, RoundRect>::value == false);
	static_assert(HasGeometry2DOverlaps<Line, Polygon>::value == false);
	static_assert(HasGeometry2DOverlaps<Line, MultiPolygon>::value == false);
	static_assert(HasGeometry2DOverlaps<LineString, Point>::value == false);
	static_assert(HasGeometry2DOverlaps<LineString, Vec2>::value == false);
	static_assert(HasGeometry2DOverlaps<LineString, Line>::value == false);
	static_assert(HasGeometry2DOverlaps<LineString, LineString>::value == false);
	static_assert(HasGeometry2DOverlaps<LineString, Bezier2>::value == false);
	static_assert(HasGeometry2DOverlaps<LineString, Bezier3>::value == false);
	static_assert(HasGeometry2DOverlaps<LineString, Rect>::value == false);
	static_assert(HasGeometry2DOverlaps<LineString, RectF>::value == false);
	static_assert(HasGeometry2DOverlaps<LineString, Circle>::value == false);
	static_assert(HasGeometry2DOverlaps<LineString, Ellipse>::value == false);
	static_assert(HasGeometry2DOverlaps<LineString, SuperEllipse>::value == false);
	static_assert(HasGeometry2DOverlaps<LineString, Triangle>::value == false);
	static_assert(HasGeometry2DOverlaps<LineString, Quad>::value == false);
	static_assert(HasGeometry2DOverlaps<LineString, RoundRect>::value == false);
	static_assert(HasGeometry2DOverlaps<LineString, Polygon>::value == false);
	static_assert(HasGeometry2DOverlaps<LineString, MultiPolygon>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier2, Point>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier2, Vec2>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier2, Line>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier2, LineString>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier2, Bezier2>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier2, Bezier3>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier2, Rect>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier2, RectF>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier2, Circle>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier2, Ellipse>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier2, SuperEllipse>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier2, Triangle>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier2, Quad>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier2, RoundRect>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier2, Polygon>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier2, MultiPolygon>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier3, Point>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier3, Vec2>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier3, Line>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier3, LineString>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier3, Bezier2>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier3, Bezier3>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier3, Rect>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier3, RectF>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier3, Circle>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier3, Ellipse>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier3, SuperEllipse>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier3, Triangle>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier3, Quad>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier3, RoundRect>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier3, Polygon>::value == false);
	static_assert(HasGeometry2DOverlaps<Bezier3, MultiPolygon>::value == false);
	static_assert(HasGeometry2DOverlaps<Rect, Point>::value == false);
	static_assert(HasGeometry2DOverlaps<Rect, Vec2>::value == false);
	static_assert(HasGeometry2DOverlaps<Rect, Line>::value == false);
	static_assert(HasGeometry2DOverlaps<Rect, LineString>::value == false);
	static_assert(HasGeometry2DOverlaps<Rect, Bezier2>::value == false);
	static_assert(HasGeometry2DOverlaps<Rect, Bezier3>::value == false);
	static_assert(HasGeometry2DOverlaps<Rect, Rect>::value);
	static_assert(HasGeometry2DOverlaps<Rect, RectF>::value);
	static_assert(HasGeometry2DOverlaps<Rect, Circle>::value);
	static_assert(HasGeometry2DOverlaps<Rect, Ellipse>::value);
	static_assert(HasGeometry2DOverlaps<Rect, SuperEllipse>::value);
	static_assert(HasGeometry2DOverlaps<Rect, Triangle>::value);
	static_assert(HasGeometry2DOverlaps<Rect, Quad>::value);
	static_assert(HasGeometry2DOverlaps<Rect, RoundRect>::value);
	static_assert(HasGeometry2DOverlaps<Rect, Polygon>::value);
	static_assert(HasGeometry2DOverlaps<Rect, MultiPolygon>::value);
	static_assert(HasGeometry2DOverlaps<RectF, Point>::value == false);
	static_assert(HasGeometry2DOverlaps<RectF, Vec2>::value == false);
	static_assert(HasGeometry2DOverlaps<RectF, Line>::value == false);
	static_assert(HasGeometry2DOverlaps<RectF, LineString>::value == false);
	static_assert(HasGeometry2DOverlaps<RectF, Bezier2>::value == false);
	static_assert(HasGeometry2DOverlaps<RectF, Bezier3>::value == false);
	static_assert(HasGeometry2DOverlaps<RectF, Rect>::value);
	static_assert(HasGeometry2DOverlaps<RectF, RectF>::value);
	static_assert(HasGeometry2DOverlaps<RectF, Circle>::value);
	static_assert(HasGeometry2DOverlaps<RectF, Ellipse>::value);
	static_assert(HasGeometry2DOverlaps<RectF, SuperEllipse>::value);
	static_assert(HasGeometry2DOverlaps<RectF, Triangle>::value);
	static_assert(HasGeometry2DOverlaps<RectF, Quad>::value);
	static_assert(HasGeometry2DOverlaps<RectF, RoundRect>::value);
	static_assert(HasGeometry2DOverlaps<RectF, Polygon>::value);
	static_assert(HasGeometry2DOverlaps<RectF, MultiPolygon>::value);
	static_assert(HasGeometry2DOverlaps<Circle, Point>::value == false);
	static_assert(HasGeometry2DOverlaps<Circle, Vec2>::value == false);
	static_assert(HasGeometry2DOverlaps<Circle, Line>::value == false);
	static_assert(HasGeometry2DOverlaps<Circle, LineString>::value == false);
	static_assert(HasGeometry2DOverlaps<Circle, Bezier2>::value == false);
	static_assert(HasGeometry2DOverlaps<Circle, Bezier3>::value == false);
	static_assert(HasGeometry2DOverlaps<Circle, Rect>::value);
	static_assert(HasGeometry2DOverlaps<Circle, RectF>::value);
	static_assert(HasGeometry2DOverlaps<Circle, Circle>::value);
	static_assert(HasGeometry2DOverlaps<Circle, Ellipse>::value);
	static_assert(HasGeometry2DOverlaps<Circle, SuperEllipse>::value);
	static_assert(HasGeometry2DOverlaps<Circle, Triangle>::value);
	static_assert(HasGeometry2DOverlaps<Circle, Quad>::value);
	static_assert(HasGeometry2DOverlaps<Circle, RoundRect>::value);
	static_assert(HasGeometry2DOverlaps<Circle, Polygon>::value);
	static_assert(HasGeometry2DOverlaps<Circle, MultiPolygon>::value);
	static_assert(HasGeometry2DOverlaps<Ellipse, Point>::value == false);
	static_assert(HasGeometry2DOverlaps<Ellipse, Vec2>::value == false);
	static_assert(HasGeometry2DOverlaps<Ellipse, Line>::value == false);
	static_assert(HasGeometry2DOverlaps<Ellipse, LineString>::value == false);
	static_assert(HasGeometry2DOverlaps<Ellipse, Bezier2>::value == false);
	static_assert(HasGeometry2DOverlaps<Ellipse, Bezier3>::value == false);
	static_assert(HasGeometry2DOverlaps<Ellipse, Rect>::value);
	static_assert(HasGeometry2DOverlaps<Ellipse, RectF>::value);
	static_assert(HasGeometry2DOverlaps<Ellipse, Circle>::value);
	static_assert(HasGeometry2DOverlaps<Ellipse, Ellipse>::value);
	static_assert(HasGeometry2DOverlaps<Ellipse, SuperEllipse>::value);
	static_assert(HasGeometry2DOverlaps<Ellipse, Triangle>::value);
	static_assert(HasGeometry2DOverlaps<Ellipse, Quad>::value);
	static_assert(HasGeometry2DOverlaps<Ellipse, RoundRect>::value);
	static_assert(HasGeometry2DOverlaps<Ellipse, Polygon>::value);
	static_assert(HasGeometry2DOverlaps<Ellipse, MultiPolygon>::value);
	static_assert(HasGeometry2DOverlaps<SuperEllipse, Point>::value == false);
	static_assert(HasGeometry2DOverlaps<SuperEllipse, Vec2>::value == false);
	static_assert(HasGeometry2DOverlaps<SuperEllipse, Line>::value == false);
	static_assert(HasGeometry2DOverlaps<SuperEllipse, LineString>::value == false);
	static_assert(HasGeometry2DOverlaps<SuperEllipse, Bezier2>::value == false);
	static_assert(HasGeometry2DOverlaps<SuperEllipse, Bezier3>::value == false);
	static_assert(HasGeometry2DOverlaps<SuperEllipse, Rect>::value);
	static_assert(HasGeometry2DOverlaps<SuperEllipse, RectF>::value);
	static_assert(HasGeometry2DOverlaps<SuperEllipse, Circle>::value);
	static_assert(HasGeometry2DOverlaps<SuperEllipse, Ellipse>::value);
	static_assert(HasGeometry2DOverlaps<SuperEllipse, SuperEllipse>::value);
	static_assert(HasGeometry2DOverlaps<SuperEllipse, Triangle>::value);
	static_assert(HasGeometry2DOverlaps<SuperEllipse, Quad>::value);
	static_assert(HasGeometry2DOverlaps<SuperEllipse, RoundRect>::value);
	static_assert(HasGeometry2DOverlaps<SuperEllipse, Polygon>::value);
	static_assert(HasGeometry2DOverlaps<SuperEllipse, MultiPolygon>::value);
	static_assert(HasGeometry2DOverlaps<Triangle, Point>::value == false);
	static_assert(HasGeometry2DOverlaps<Triangle, Vec2>::value == false);
	static_assert(HasGeometry2DOverlaps<Triangle, Line>::value == false);
	static_assert(HasGeometry2DOverlaps<Triangle, LineString>::value == false);
	static_assert(HasGeometry2DOverlaps<Triangle, Bezier2>::value == false);
	static_assert(HasGeometry2DOverlaps<Triangle, Bezier3>::value == false);
	static_assert(HasGeometry2DOverlaps<Triangle, Rect>::value);
	static_assert(HasGeometry2DOverlaps<Triangle, RectF>::value);
	static_assert(HasGeometry2DOverlaps<Triangle, Circle>::value);
	static_assert(HasGeometry2DOverlaps<Triangle, Ellipse>::value);
	static_assert(HasGeometry2DOverlaps<Triangle, SuperEllipse>::value);
	static_assert(HasGeometry2DOverlaps<Triangle, Triangle>::value);
	static_assert(HasGeometry2DOverlaps<Triangle, Quad>::value);
	static_assert(HasGeometry2DOverlaps<Triangle, RoundRect>::value);
	static_assert(HasGeometry2DOverlaps<Triangle, Polygon>::value);
	static_assert(HasGeometry2DOverlaps<Triangle, MultiPolygon>::value);
	static_assert(HasGeometry2DOverlaps<Quad, Point>::value == false);
	static_assert(HasGeometry2DOverlaps<Quad, Vec2>::value == false);
	static_assert(HasGeometry2DOverlaps<Quad, Line>::value == false);
	static_assert(HasGeometry2DOverlaps<Quad, LineString>::value == false);
	static_assert(HasGeometry2DOverlaps<Quad, Bezier2>::value == false);
	static_assert(HasGeometry2DOverlaps<Quad, Bezier3>::value == false);
	static_assert(HasGeometry2DOverlaps<Quad, Rect>::value);
	static_assert(HasGeometry2DOverlaps<Quad, RectF>::value);
	static_assert(HasGeometry2DOverlaps<Quad, Circle>::value);
	static_assert(HasGeometry2DOverlaps<Quad, Ellipse>::value);
	static_assert(HasGeometry2DOverlaps<Quad, SuperEllipse>::value);
	static_assert(HasGeometry2DOverlaps<Quad, Triangle>::value);
	static_assert(HasGeometry2DOverlaps<Quad, Quad>::value);
	static_assert(HasGeometry2DOverlaps<Quad, RoundRect>::value);
	static_assert(HasGeometry2DOverlaps<Quad, Polygon>::value);
	static_assert(HasGeometry2DOverlaps<Quad, MultiPolygon>::value);
	static_assert(HasGeometry2DOverlaps<RoundRect, Point>::value == false);
	static_assert(HasGeometry2DOverlaps<RoundRect, Vec2>::value == false);
	static_assert(HasGeometry2DOverlaps<RoundRect, Line>::value == false);
	static_assert(HasGeometry2DOverlaps<RoundRect, LineString>::value == false);
	static_assert(HasGeometry2DOverlaps<RoundRect, Bezier2>::value == false);
	static_assert(HasGeometry2DOverlaps<RoundRect, Bezier3>::value == false);
	static_assert(HasGeometry2DOverlaps<RoundRect, Rect>::value);
	static_assert(HasGeometry2DOverlaps<RoundRect, RectF>::value);
	static_assert(HasGeometry2DOverlaps<RoundRect, Circle>::value);
	static_assert(HasGeometry2DOverlaps<RoundRect, Ellipse>::value);
	static_assert(HasGeometry2DOverlaps<RoundRect, SuperEllipse>::value);
	static_assert(HasGeometry2DOverlaps<RoundRect, Triangle>::value);
	static_assert(HasGeometry2DOverlaps<RoundRect, Quad>::value);
	static_assert(HasGeometry2DOverlaps<RoundRect, RoundRect>::value);
	static_assert(HasGeometry2DOverlaps<RoundRect, Polygon>::value);
	static_assert(HasGeometry2DOverlaps<RoundRect, MultiPolygon>::value);
	static_assert(HasGeometry2DOverlaps<Polygon, Point>::value == false);
	static_assert(HasGeometry2DOverlaps<Polygon, Vec2>::value == false);
	static_assert(HasGeometry2DOverlaps<Polygon, Line>::value == false);
	static_assert(HasGeometry2DOverlaps<Polygon, LineString>::value == false);
	static_assert(HasGeometry2DOverlaps<Polygon, Bezier2>::value == false);
	static_assert(HasGeometry2DOverlaps<Polygon, Bezier3>::value == false);
	static_assert(HasGeometry2DOverlaps<Polygon, Rect>::value);
	static_assert(HasGeometry2DOverlaps<Polygon, RectF>::value);
	static_assert(HasGeometry2DOverlaps<Polygon, Circle>::value);
	static_assert(HasGeometry2DOverlaps<Polygon, Ellipse>::value);
	static_assert(HasGeometry2DOverlaps<Polygon, SuperEllipse>::value);
	static_assert(HasGeometry2DOverlaps<Polygon, Triangle>::value);
	static_assert(HasGeometry2DOverlaps<Polygon, Quad>::value);
	static_assert(HasGeometry2DOverlaps<Polygon, RoundRect>::value);
	static_assert(HasGeometry2DOverlaps<Polygon, Polygon>::value);
	static_assert(HasGeometry2DOverlaps<Polygon, MultiPolygon>::value);
	static_assert(HasGeometry2DOverlaps<MultiPolygon, Point>::value == false);
	static_assert(HasGeometry2DOverlaps<MultiPolygon, Vec2>::value == false);
	static_assert(HasGeometry2DOverlaps<MultiPolygon, Line>::value == false);
	static_assert(HasGeometry2DOverlaps<MultiPolygon, LineString>::value == false);
	static_assert(HasGeometry2DOverlaps<MultiPolygon, Bezier2>::value == false);
	static_assert(HasGeometry2DOverlaps<MultiPolygon, Bezier3>::value == false);
	static_assert(HasGeometry2DOverlaps<MultiPolygon, Rect>::value);
	static_assert(HasGeometry2DOverlaps<MultiPolygon, RectF>::value);
	static_assert(HasGeometry2DOverlaps<MultiPolygon, Circle>::value);
	static_assert(HasGeometry2DOverlaps<MultiPolygon, Ellipse>::value);
	static_assert(HasGeometry2DOverlaps<MultiPolygon, SuperEllipse>::value);
	static_assert(HasGeometry2DOverlaps<MultiPolygon, Triangle>::value);
	static_assert(HasGeometry2DOverlaps<MultiPolygon, Quad>::value);
	static_assert(HasGeometry2DOverlaps<MultiPolygon, RoundRect>::value);
	static_assert(HasGeometry2DOverlaps<MultiPolygon, Polygon>::value);
	static_assert(HasGeometry2DOverlaps<MultiPolygon, MultiPolygon>::value);
}
