//-----------------------------------------------
//
//	This file is part of the Siv3D Engine.
//
//	Licensed under the MIT License.
//
//-----------------------------------------------

# include "Siv3DTest.hpp"
# include <type_traits>
# include <utility>
# include <Siv3D/Geometry2D/Distance.hpp>

namespace
{
	template <class A, class B, class = void>
	struct HasDistanceToMember : std::false_type {};

	template <class A, class B>
	struct HasDistanceToMember<A, B, std::void_t<decltype(
		std::declval<const A&>().distanceTo(std::declval<const B&>()))>>
		: std::is_same<decltype(std::declval<const A&>().distanceTo(
			std::declval<const B&>())), double> {};
}

TEST_CASE("Geometry2D.Distance.MemberAvailability")
{
	static_assert(HasDistanceToMember<Point, Point>::value);
	static_assert(HasDistanceToMember<Point, Vec2>::value);
	static_assert(HasDistanceToMember<Point, Line>::value);
	static_assert(HasDistanceToMember<Point, LineString>::value);
	static_assert(HasDistanceToMember<Point, Bezier2>::value);
	static_assert(HasDistanceToMember<Point, Bezier3>::value);
	static_assert(HasDistanceToMember<Point, Rect>::value);
	static_assert(HasDistanceToMember<Point, RectF>::value);
	static_assert(HasDistanceToMember<Point, Circle>::value);
	static_assert(HasDistanceToMember<Point, Ellipse>::value);
	static_assert(HasDistanceToMember<Point, SuperEllipse>::value);
	static_assert(HasDistanceToMember<Point, Triangle>::value);
	static_assert(HasDistanceToMember<Point, Quad>::value);
	static_assert(HasDistanceToMember<Point, RoundRect>::value);
	static_assert(HasDistanceToMember<Point, Polygon>::value);
	static_assert(HasDistanceToMember<Point, MultiPolygon>::value);
	static_assert(HasDistanceToMember<Vec2, Point>::value);
	static_assert(HasDistanceToMember<Vec2, Vec2>::value);
	static_assert(HasDistanceToMember<Vec2, Line>::value);
	static_assert(HasDistanceToMember<Vec2, LineString>::value);
	static_assert(HasDistanceToMember<Vec2, Bezier2>::value);
	static_assert(HasDistanceToMember<Vec2, Bezier3>::value);
	static_assert(HasDistanceToMember<Vec2, Rect>::value);
	static_assert(HasDistanceToMember<Vec2, RectF>::value);
	static_assert(HasDistanceToMember<Vec2, Circle>::value);
	static_assert(HasDistanceToMember<Vec2, Ellipse>::value);
	static_assert(HasDistanceToMember<Vec2, SuperEllipse>::value);
	static_assert(HasDistanceToMember<Vec2, Triangle>::value);
	static_assert(HasDistanceToMember<Vec2, Quad>::value);
	static_assert(HasDistanceToMember<Vec2, RoundRect>::value);
	static_assert(HasDistanceToMember<Vec2, Polygon>::value);
	static_assert(HasDistanceToMember<Vec2, MultiPolygon>::value);
	static_assert(HasDistanceToMember<Line, Point>::value);
	static_assert(HasDistanceToMember<Line, Vec2>::value);
	static_assert(HasDistanceToMember<Line, Line>::value);
	static_assert(HasDistanceToMember<Line, LineString>::value);
	static_assert(HasDistanceToMember<Line, Bezier2>::value);
	static_assert(HasDistanceToMember<Line, Bezier3>::value);
	static_assert(HasDistanceToMember<Line, Rect>::value);
	static_assert(HasDistanceToMember<Line, RectF>::value);
	static_assert(HasDistanceToMember<Line, Circle>::value);
	static_assert(HasDistanceToMember<Line, Ellipse>::value);
	static_assert(HasDistanceToMember<Line, SuperEllipse>::value);
	static_assert(HasDistanceToMember<Line, Triangle>::value);
	static_assert(HasDistanceToMember<Line, Quad>::value);
	static_assert(HasDistanceToMember<Line, RoundRect>::value);
	static_assert(HasDistanceToMember<Line, Polygon>::value);
	static_assert(HasDistanceToMember<Line, MultiPolygon>::value);
	static_assert(HasDistanceToMember<LineString, Point>::value);
	static_assert(HasDistanceToMember<LineString, Vec2>::value);
	static_assert(HasDistanceToMember<LineString, Line>::value);
	static_assert(HasDistanceToMember<LineString, LineString>::value);
	static_assert(HasDistanceToMember<LineString, Bezier2>::value);
	static_assert(HasDistanceToMember<LineString, Bezier3>::value);
	static_assert(HasDistanceToMember<LineString, Rect>::value);
	static_assert(HasDistanceToMember<LineString, RectF>::value);
	static_assert(HasDistanceToMember<LineString, Circle>::value);
	static_assert(HasDistanceToMember<LineString, Ellipse>::value);
	static_assert(HasDistanceToMember<LineString, SuperEllipse>::value);
	static_assert(HasDistanceToMember<LineString, Triangle>::value);
	static_assert(HasDistanceToMember<LineString, Quad>::value);
	static_assert(HasDistanceToMember<LineString, RoundRect>::value);
	static_assert(HasDistanceToMember<LineString, Polygon>::value);
	static_assert(HasDistanceToMember<LineString, MultiPolygon>::value);
	static_assert(HasDistanceToMember<Bezier2, Point>::value);
	static_assert(HasDistanceToMember<Bezier2, Vec2>::value);
	static_assert(HasDistanceToMember<Bezier2, Line>::value);
	static_assert(HasDistanceToMember<Bezier2, LineString>::value);
	static_assert(HasDistanceToMember<Bezier2, Bezier2>::value);
	static_assert(HasDistanceToMember<Bezier2, Bezier3>::value);
	static_assert(HasDistanceToMember<Bezier2, Rect>::value);
	static_assert(HasDistanceToMember<Bezier2, RectF>::value);
	static_assert(HasDistanceToMember<Bezier2, Circle>::value);
	static_assert(HasDistanceToMember<Bezier2, Ellipse>::value);
	static_assert(HasDistanceToMember<Bezier2, SuperEllipse>::value);
	static_assert(HasDistanceToMember<Bezier2, Triangle>::value);
	static_assert(HasDistanceToMember<Bezier2, Quad>::value);
	static_assert(HasDistanceToMember<Bezier2, RoundRect>::value);
	static_assert(HasDistanceToMember<Bezier2, Polygon>::value);
	static_assert(HasDistanceToMember<Bezier2, MultiPolygon>::value);
	static_assert(HasDistanceToMember<Bezier3, Point>::value);
	static_assert(HasDistanceToMember<Bezier3, Vec2>::value);
	static_assert(HasDistanceToMember<Bezier3, Line>::value);
	static_assert(HasDistanceToMember<Bezier3, LineString>::value);
	static_assert(HasDistanceToMember<Bezier3, Bezier2>::value);
	static_assert(HasDistanceToMember<Bezier3, Bezier3>::value);
	static_assert(HasDistanceToMember<Bezier3, Rect>::value);
	static_assert(HasDistanceToMember<Bezier3, RectF>::value);
	static_assert(HasDistanceToMember<Bezier3, Circle>::value);
	static_assert(HasDistanceToMember<Bezier3, Ellipse>::value);
	static_assert(HasDistanceToMember<Bezier3, SuperEllipse>::value);
	static_assert(HasDistanceToMember<Bezier3, Triangle>::value);
	static_assert(HasDistanceToMember<Bezier3, Quad>::value);
	static_assert(HasDistanceToMember<Bezier3, RoundRect>::value);
	static_assert(HasDistanceToMember<Bezier3, Polygon>::value);
	static_assert(HasDistanceToMember<Bezier3, MultiPolygon>::value);
	static_assert(HasDistanceToMember<Rect, Point>::value);
	static_assert(HasDistanceToMember<Rect, Vec2>::value);
	static_assert(HasDistanceToMember<Rect, Line>::value);
	static_assert(HasDistanceToMember<Rect, LineString>::value);
	static_assert(HasDistanceToMember<Rect, Bezier2>::value);
	static_assert(HasDistanceToMember<Rect, Bezier3>::value);
	static_assert(HasDistanceToMember<Rect, Rect>::value);
	static_assert(HasDistanceToMember<Rect, RectF>::value);
	static_assert(HasDistanceToMember<Rect, Circle>::value);
	static_assert(HasDistanceToMember<Rect, Ellipse>::value);
	static_assert(HasDistanceToMember<Rect, SuperEllipse>::value);
	static_assert(HasDistanceToMember<Rect, Triangle>::value);
	static_assert(HasDistanceToMember<Rect, Quad>::value);
	static_assert(HasDistanceToMember<Rect, RoundRect>::value);
	static_assert(HasDistanceToMember<Rect, Polygon>::value);
	static_assert(HasDistanceToMember<Rect, MultiPolygon>::value);
	static_assert(HasDistanceToMember<RectF, Point>::value);
	static_assert(HasDistanceToMember<RectF, Vec2>::value);
	static_assert(HasDistanceToMember<RectF, Line>::value);
	static_assert(HasDistanceToMember<RectF, LineString>::value);
	static_assert(HasDistanceToMember<RectF, Bezier2>::value);
	static_assert(HasDistanceToMember<RectF, Bezier3>::value);
	static_assert(HasDistanceToMember<RectF, Rect>::value);
	static_assert(HasDistanceToMember<RectF, RectF>::value);
	static_assert(HasDistanceToMember<RectF, Circle>::value);
	static_assert(HasDistanceToMember<RectF, Ellipse>::value);
	static_assert(HasDistanceToMember<RectF, SuperEllipse>::value);
	static_assert(HasDistanceToMember<RectF, Triangle>::value);
	static_assert(HasDistanceToMember<RectF, Quad>::value);
	static_assert(HasDistanceToMember<RectF, RoundRect>::value);
	static_assert(HasDistanceToMember<RectF, Polygon>::value);
	static_assert(HasDistanceToMember<RectF, MultiPolygon>::value);
	static_assert(HasDistanceToMember<Circle, Point>::value);
	static_assert(HasDistanceToMember<Circle, Vec2>::value);
	static_assert(HasDistanceToMember<Circle, Line>::value);
	static_assert(HasDistanceToMember<Circle, LineString>::value);
	static_assert(HasDistanceToMember<Circle, Bezier2>::value);
	static_assert(HasDistanceToMember<Circle, Bezier3>::value);
	static_assert(HasDistanceToMember<Circle, Rect>::value);
	static_assert(HasDistanceToMember<Circle, RectF>::value);
	static_assert(HasDistanceToMember<Circle, Circle>::value);
	static_assert(HasDistanceToMember<Circle, Ellipse>::value);
	static_assert(HasDistanceToMember<Circle, SuperEllipse>::value);
	static_assert(HasDistanceToMember<Circle, Triangle>::value);
	static_assert(HasDistanceToMember<Circle, Quad>::value);
	static_assert(HasDistanceToMember<Circle, RoundRect>::value);
	static_assert(HasDistanceToMember<Circle, Polygon>::value);
	static_assert(HasDistanceToMember<Circle, MultiPolygon>::value);
	static_assert(HasDistanceToMember<Ellipse, Point>::value);
	static_assert(HasDistanceToMember<Ellipse, Vec2>::value);
	static_assert(HasDistanceToMember<Ellipse, Line>::value);
	static_assert(HasDistanceToMember<Ellipse, LineString>::value);
	static_assert(HasDistanceToMember<Ellipse, Bezier2>::value);
	static_assert(HasDistanceToMember<Ellipse, Bezier3>::value);
	static_assert(HasDistanceToMember<Ellipse, Rect>::value);
	static_assert(HasDistanceToMember<Ellipse, RectF>::value);
	static_assert(HasDistanceToMember<Ellipse, Circle>::value);
	static_assert(HasDistanceToMember<Ellipse, Ellipse>::value);
	static_assert(HasDistanceToMember<Ellipse, SuperEllipse>::value);
	static_assert(HasDistanceToMember<Ellipse, Triangle>::value);
	static_assert(HasDistanceToMember<Ellipse, Quad>::value);
	static_assert(HasDistanceToMember<Ellipse, RoundRect>::value);
	static_assert(HasDistanceToMember<Ellipse, Polygon>::value);
	static_assert(HasDistanceToMember<Ellipse, MultiPolygon>::value);
	static_assert(HasDistanceToMember<SuperEllipse, Point>::value);
	static_assert(HasDistanceToMember<SuperEllipse, Vec2>::value);
	static_assert(HasDistanceToMember<SuperEllipse, Line>::value);
	static_assert(HasDistanceToMember<SuperEllipse, LineString>::value);
	static_assert(HasDistanceToMember<SuperEllipse, Bezier2>::value);
	static_assert(HasDistanceToMember<SuperEllipse, Bezier3>::value);
	static_assert(HasDistanceToMember<SuperEllipse, Rect>::value);
	static_assert(HasDistanceToMember<SuperEllipse, RectF>::value);
	static_assert(HasDistanceToMember<SuperEllipse, Circle>::value);
	static_assert(HasDistanceToMember<SuperEllipse, Ellipse>::value);
	static_assert(HasDistanceToMember<SuperEllipse, SuperEllipse>::value);
	static_assert(HasDistanceToMember<SuperEllipse, Triangle>::value);
	static_assert(HasDistanceToMember<SuperEllipse, Quad>::value);
	static_assert(HasDistanceToMember<SuperEllipse, RoundRect>::value);
	static_assert(HasDistanceToMember<SuperEllipse, Polygon>::value);
	static_assert(HasDistanceToMember<SuperEllipse, MultiPolygon>::value);
	static_assert(HasDistanceToMember<Triangle, Point>::value);
	static_assert(HasDistanceToMember<Triangle, Vec2>::value);
	static_assert(HasDistanceToMember<Triangle, Line>::value);
	static_assert(HasDistanceToMember<Triangle, LineString>::value);
	static_assert(HasDistanceToMember<Triangle, Bezier2>::value);
	static_assert(HasDistanceToMember<Triangle, Bezier3>::value);
	static_assert(HasDistanceToMember<Triangle, Rect>::value);
	static_assert(HasDistanceToMember<Triangle, RectF>::value);
	static_assert(HasDistanceToMember<Triangle, Circle>::value);
	static_assert(HasDistanceToMember<Triangle, Ellipse>::value);
	static_assert(HasDistanceToMember<Triangle, SuperEllipse>::value);
	static_assert(HasDistanceToMember<Triangle, Triangle>::value);
	static_assert(HasDistanceToMember<Triangle, Quad>::value);
	static_assert(HasDistanceToMember<Triangle, RoundRect>::value);
	static_assert(HasDistanceToMember<Triangle, Polygon>::value);
	static_assert(HasDistanceToMember<Triangle, MultiPolygon>::value);
	static_assert(HasDistanceToMember<Quad, Point>::value);
	static_assert(HasDistanceToMember<Quad, Vec2>::value);
	static_assert(HasDistanceToMember<Quad, Line>::value);
	static_assert(HasDistanceToMember<Quad, LineString>::value);
	static_assert(HasDistanceToMember<Quad, Bezier2>::value);
	static_assert(HasDistanceToMember<Quad, Bezier3>::value);
	static_assert(HasDistanceToMember<Quad, Rect>::value);
	static_assert(HasDistanceToMember<Quad, RectF>::value);
	static_assert(HasDistanceToMember<Quad, Circle>::value);
	static_assert(HasDistanceToMember<Quad, Ellipse>::value);
	static_assert(HasDistanceToMember<Quad, SuperEllipse>::value);
	static_assert(HasDistanceToMember<Quad, Triangle>::value);
	static_assert(HasDistanceToMember<Quad, Quad>::value);
	static_assert(HasDistanceToMember<Quad, RoundRect>::value);
	static_assert(HasDistanceToMember<Quad, Polygon>::value);
	static_assert(HasDistanceToMember<Quad, MultiPolygon>::value);
	static_assert(HasDistanceToMember<RoundRect, Point>::value);
	static_assert(HasDistanceToMember<RoundRect, Vec2>::value);
	static_assert(HasDistanceToMember<RoundRect, Line>::value);
	static_assert(HasDistanceToMember<RoundRect, LineString>::value);
	static_assert(HasDistanceToMember<RoundRect, Bezier2>::value);
	static_assert(HasDistanceToMember<RoundRect, Bezier3>::value);
	static_assert(HasDistanceToMember<RoundRect, Rect>::value);
	static_assert(HasDistanceToMember<RoundRect, RectF>::value);
	static_assert(HasDistanceToMember<RoundRect, Circle>::value);
	static_assert(HasDistanceToMember<RoundRect, Ellipse>::value);
	static_assert(HasDistanceToMember<RoundRect, SuperEllipse>::value);
	static_assert(HasDistanceToMember<RoundRect, Triangle>::value);
	static_assert(HasDistanceToMember<RoundRect, Quad>::value);
	static_assert(HasDistanceToMember<RoundRect, RoundRect>::value);
	static_assert(HasDistanceToMember<RoundRect, Polygon>::value);
	static_assert(HasDistanceToMember<RoundRect, MultiPolygon>::value);
	static_assert(HasDistanceToMember<Polygon, Point>::value);
	static_assert(HasDistanceToMember<Polygon, Vec2>::value);
	static_assert(HasDistanceToMember<Polygon, Line>::value);
	static_assert(HasDistanceToMember<Polygon, LineString>::value);
	static_assert(HasDistanceToMember<Polygon, Bezier2>::value);
	static_assert(HasDistanceToMember<Polygon, Bezier3>::value);
	static_assert(HasDistanceToMember<Polygon, Rect>::value);
	static_assert(HasDistanceToMember<Polygon, RectF>::value);
	static_assert(HasDistanceToMember<Polygon, Circle>::value);
	static_assert(HasDistanceToMember<Polygon, Ellipse>::value);
	static_assert(HasDistanceToMember<Polygon, SuperEllipse>::value);
	static_assert(HasDistanceToMember<Polygon, Triangle>::value);
	static_assert(HasDistanceToMember<Polygon, Quad>::value);
	static_assert(HasDistanceToMember<Polygon, RoundRect>::value);
	static_assert(HasDistanceToMember<Polygon, Polygon>::value);
	static_assert(HasDistanceToMember<Polygon, MultiPolygon>::value);
	static_assert(HasDistanceToMember<MultiPolygon, Point>::value);
	static_assert(HasDistanceToMember<MultiPolygon, Vec2>::value);
	static_assert(HasDistanceToMember<MultiPolygon, Line>::value);
	static_assert(HasDistanceToMember<MultiPolygon, LineString>::value);
	static_assert(HasDistanceToMember<MultiPolygon, Bezier2>::value);
	static_assert(HasDistanceToMember<MultiPolygon, Bezier3>::value);
	static_assert(HasDistanceToMember<MultiPolygon, Rect>::value);
	static_assert(HasDistanceToMember<MultiPolygon, RectF>::value);
	static_assert(HasDistanceToMember<MultiPolygon, Circle>::value);
	static_assert(HasDistanceToMember<MultiPolygon, Ellipse>::value);
	static_assert(HasDistanceToMember<MultiPolygon, SuperEllipse>::value);
	static_assert(HasDistanceToMember<MultiPolygon, Triangle>::value);
	static_assert(HasDistanceToMember<MultiPolygon, Quad>::value);
	static_assert(HasDistanceToMember<MultiPolygon, RoundRect>::value);
	static_assert(HasDistanceToMember<MultiPolygon, Polygon>::value);
	static_assert(HasDistanceToMember<MultiPolygon, MultiPolygon>::value);
}
