//-----------------------------------------------
//
//	This file is part of the Siv3D Engine.
//
//	Copyright (c) 2008-2022 Ryo Suzuki
//	Copyright (c) 2016-2022 OpenSiv3D Project
//
//	Licensed under the MIT License.
//
//-----------------------------------------------

# pragma once
# include <array>
# include <ThirdParty/pcg/pcg_random.hpp>

namespace s3d
{
	namespace PRNG
	{
		class PCG64
		{
		public:

			using engine_type	= ::pcg64;

			using result_type	= engine_type::result_type;

			using state_type	= std::array<uint64, 2>;

			[[nodiscard]]
			PCG64()
				: m_rng{} {}

			[[nodiscard]]
			explicit PCG64(uint64 seed)
				: m_rng{ seed } {}

			[[nodiscard]]
			explicit PCG64(const state_type& seeds)
				: m_rng{ PCG_128BIT_CONSTANT(seeds[0], seeds[1]) } {}

			void seed(uint64 seed) noexcept
			{
				m_rng.seed(seed);
			}

			void seed(const state_type& seeds) noexcept
			{
				m_rng.seed(PCG_128BIT_CONSTANT(seeds[0], seeds[1]));
			}

			/// @brief 生成される乱数の最小値を返します。 | Returns the minimum value potentially generated by the random-number engine
			/// @return 生成される乱数の最小値 | The minimum potentially generated value
			[[nodiscard]]
			static constexpr result_type min() noexcept
			{
				return engine_type::min();
			}

			/// @brief 生成される乱数の最大値を返します。 | Returns the maximum value potentially generated by the random-number engine.
			/// @return 生成される乱数の最大値 | The maximum potentially generated value
			[[nodiscard]]
			static constexpr result_type max() noexcept
			{
				return engine_type::max();
			}

			/// @brief 乱数を生成します。 | Generates a pseudo-random value.
			/// @return 生成された乱数 | A generated pseudo-random value
			result_type operator ()() noexcept
			{
				return m_rng();
			}

		private:

			engine_type m_rng;
		};
	}
}
